# Generated by Django 6.0.1 on 2026-02-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
