# Generated by Django 6.0.1 on 2026-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='slug',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
