# Generated by Django 6.0.1 on 2026-02-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applicant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='slug',
        ),
    ]
