# Generated by Django 6.0.1 on 2026-02-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={'ordering': ['question', 'answer']},
        ),
        migrations.AlterModelTable(
            name='joke',
            table='jokes',
        ),
    ]
