# Generated by Django 6.0.1 on 2026-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_alter_joke_options_alter_joke_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={},
        ),
        migrations.AddField(
            model_name='joke',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='joke',
            table=None,
        ),
    ]
