# Generated by Django 6.0.1 on 2026-02-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_alter_joke_options_joke_slug_alter_joke_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
