# Generated by Django 6.0.1 on 2026-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_alter_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='answer',
            field=models.TextField(blank=True, help_text='The second part of the joke', max_length=100),
        ),
        migrations.AlterField(
            model_name='joke',
            name='question',
            field=models.TextField(help_text='The first part of the joke', max_length=200),
        ),
    ]
