# Generated by Django 6.0.1 on 2026-02-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_tag_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': ('Categories',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
