# Generated by Django 6.0.1 on 2026-02-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0010_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
    ]
